[package]
name = "saleor-dockerize-all-apps"
version = "0.1.0"
edition = "2021"

[dependencies]
# owo-colors = "4.0.0"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
spinners = "4.1.1"
thiserror = "1.0.58"
walkdir = "2.5.0"
