[tasks.apply-changes]
alias = "apply-changes"
script = '''
./changes.sh
'''
# Configures the default task to run
[tasks.default]
alias = "build-containers"

# Overrides the default build task
[tasks.build]
alias = "build-containers"


[tasks.build-simple-payment-gateway]
script = '''
docker build --rm --target chef-simple-payment-gateway .
docker tag $(docker image ls -q --filter=label=service=chef-simple-payment-gateway) ghcr.io/djkato/saleor-simple-payment-gateway
'''

[tasks.build-containers]
dependencies = [
  "delete-images",
  "apply-changes",
  "build-",
  "build-simple-payment-gateway",
]

[tasks.push-containers]
script = '''
docker push ghcr.io/djkato/saleor-sitemap-generator:latest
docker push ghcr.io/djkato/saleor-simple-payment-gateway:latest
'''

[tasks.delete-images]
script = '''
docker rmi -f $(docker image ls -q --filter=label=service=chef-sitemap-generator) 2>&1 || true
docker rmi -f $(docker image ls -q --filter=label=service=chef-simple-payment-gateway) 2>&1 || true
'''
## DEPRECATED APPS:

# abandoned checkouts needs no further patches :)

# SKIP_ENV_VALIDATION=true pnpm run build
[tasks.build-payment-authorized-net]
script = '''
cd all_apps/saleor-app-payment-authorized.net
rm -rf example


docker build --rm --target chef-sitemap-generator .
docker tag $(docker image ls -q --filter=label=service=chef-sitemap-generator) ghcr.io/djkato/saleor-sitemap-generator
'''
